# Generated by Django 5.1.2 on 2024-10-16 20:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_profile_k0eomt', max_length=255, verbose_name='image'),
        ),
    ]
